# SVD 
## Getting Started with  $$Singular Value Decomposition $$  in Python
### https://www.section.io/engineering-education/singular-value-decomposition-in-python/

In [2]:
import numpy as np
from scipy.linalg import svd

In [17]:
# define a matrix
A = np.array([[3, 1, 1], [-1, 3, 1]])
print("A=",A)

# SVD
U, S, V_T = svd(A)

# left singular vectors
print("\n U=",U)

# singular values
print("\nS=",S)

#right singular vectors
print("\nV_T=",V_T)


A= [[ 3  1  1]
 [-1  3  1]]

 U= [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S= [3.46410162 3.16227766]

V_T= [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.27355937e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [8]:
S_diag = np.array([[3.46410162, 0, 0], [0, 3.16227766, 0]])
S_diag


array([[3.46410162, 0.        , 0.        ],
       [0.        , 3.16227766, 0.        ]])

In [9]:
B = U.dot(S_diag.dot(V_T))
print("Reconstructed matrix:")
print(B)

Reconstructed matrix:
[[ 3.  1.  1.]
 [-1.  3.  1.]]


In [ ]:
import numpy as np
from scipy.linalg import svd
# define a matrix
A = np.array([[3, 1, 1], [-1, 3, 1]])
print("A=",A)

# SVD
U, S, V_T = svd(A)

# left singular vectors
print("\n U=",U)

# singular values
print("\nS=",S)

#right singular vectors
print("\nV_T=",V_T)

S_diag = np.array([[3.46410162, 0, 0], [0, 3.16227766, 0]])
S_diag
B = U.dot(S_diag.dot(V_T))
print("Reconstructed matrix:")
print(B)


### AAT
### λ1=10 
### λ2=12 The Eigenvectors corresponding to the above
### u⃗ 1=[1 1] ,and
### u⃗ 2=[1 −1]

### Gram-Schimidt process
### v⃗ 1=u⃗ 1
### w⃗ =v⃗ 1|v⃗ 1|=[12√ 12√]
### v⃗ 2=u⃗ 2−<u⃗ 2,v⃗ 1><v⃗ 1,v⃗ 1>v⃗ 1

### v⃗ 2=[1 −1]−0[1 1]=[1 −1]−[0,0]=[1 −1]
### w⃗ 2=v⃗ 2|v⃗ 2|=[12√,−12√]

### Therefore; U=[12√12√ 12√−12√ ]

#### 
#### 
#### 
#### 


#### a=A.dot(A.T)   #  or ===> a=dot(A,A.T)
#### eigenvalue,eigenvector=np.linalg.eig(a)
#### print('vector proprios')
#### for i in range(len(eigenvalue)):
####     print('lambda',i+1,":",eigenvalue[i])

    
#### #out_put    
#### vector proprios
#### lambda 1 : 12.0
#### lambda 2 : 10.0

#  **********************    gram-schmitd   ******************


def gs_cofficient(v1, v2): 
    return np.dot(v2, v1) / np.dot(v1, v1) 

def multiply(cofficient, v):
    return map((lambda x : x * cofficient), v) 

def proj(v1, v2):
    return multiply(gs_cofficient(v1, v2) , v1) 

def gs(X):
    Y = [] 
    for i in range(len(X)):
        temp_vec = X[i] 
        for inY in Y :
            proj_vec = proj(inY, X[i]) 
            #print "i =", i, ", projection vector =", proj_vec 
            temp_vec = map(lambda x, y : x - y, temp_vec, proj_vec) 
            #print("i =", i, ", temporary vector =",temp_vec 
        Y.append(temp_vec)
    return Y 
 
    
test = np.array([[3, 1, 1], [-1, 3, 1]])
test2 = np.array([[1.0, 1.0, 0.0], [1.0, 3.0, 1.0], [2.0, -1.0, 1.0]]) 
print(np.array(gs(test))
print(np.array(gs(test2))
      
      

# ATA

λ1=12 , λ2=10, and λ3=0 The respective eigenvector for the above λ values are:

u⃗ 1=[1 2 1]
u⃗ 2=[2 −1 0]
u⃗ 3=[1 2 −5]


Gram-Schimidt process

v⃗ 1=u⃗ 1
w⃗ 1=v⃗ 1|v⃗ 1|=[16√,26√,16√]
v⃗ 2=u⃗ 2−<u⃗ 2,v⃗ 1><v⃗ 1,v⃗ 1>v⃗ 1
v⃗ 2=[2,−1,0]
w⃗ 2=v⃗ 2|v⃗ 2|=[25√,−15√,0]
v⃗ 3=u⃗ 3−<u⃗ 3,v⃗ 1><v⃗ 1,v⃗ 1>v⃗ 1−<u⃗ 3,v⃗ 2><v⃗ 2,v⃗ 2>v⃗ 2=[−23,−23,103]

w⃗ 3=v⃗ 3|v⃗ 3|=[13√0,23√0,−53√0]
Therefore: V=[16√25√13√0 26√−15√23√0 16√0−53√0 ]
VT=[16√26√16√ 25√−15√0 13√023√0−53√0]



## UΣVT=[12√12√ 12√−12√ ][1–√200 01–√00] 
## [16√26√16√ 25√−15√0 13√023√0−53√0]=[311 −131]=A

# $SVD$
### https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/

#### This tutorial is divided into 5 parts; they are:

#### Singular-Value Decomposition
#### Calculate Singular-Value Decomposition
#### Reconstruct Matrix from SVD
#### SVD for Pseudoinverse
#### SVD for Dimensionality Reduction


In [18]:
import numpy as np
from scipy.linalg import svd
import pandas as pd


# define a matrix
A = np.array([[3, 1, 1], [-1, 3, 1]])
print("A=",A)

# SVD
U, S, V_T = svd(A)

# left singular vectors
print("\n U=",U)

# singular values
print("\nS=",S)

#right singular vectors
print("\nV_T=",V_T)


A= [[ 3  1  1]
 [-1  3  1]]

 U= [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S= [3.46410162 3.16227766]

V_T= [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.27355937e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [19]:
ANS=U.dot(S,V_T)

ValueError: output array is not acceptable (must have the right datatype, number of dimensions, and be a C-Array)

In [22]:
# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)


# create m x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(VT))

print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [39]:
A.shape[1]  #  =2
A.shape[-1] #  =3
A.shape[0]  #  =3


3

In [25]:
ans=A.shape[1]
Sigma[:ans, :ans] = np.diag(s)
Sigma


array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [35]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create n x n Sigma matrix
Sigma = np.diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [33]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# Singular-value decomposition
U, S, VT = svd(A)
# create n x n Sigma matrix
#Sigma = np.diag(s)
# reconstruct matrix
B = U.dot(S.dot(VT))
print(B,"\n","\n",S,"\n","\n",U,"\n","\n",VT)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[-11.01480989  10.81497867   6.83448604] 
 
 [1.68481034e+01 1.06836951e+00 4.41842475e-16] 
 
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]] 
 
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [37]:
U*Sigma*VT
B = U.dot(Sigma.dot(VT))
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# reduce 

In [47]:

from scipy.linalg import svd
A = np.array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] =np.diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [48]:
from sklearn.decomposition import TruncatedSVD
# define array
A = np.array([[1,2,3,4,5,6,7,8,9,10],
            [11,12,13,14,15,16,17,18,19,20],
            [21,22,23,24,25,26,27,28,29,30]])
print(A)
# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


# 

## https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html

In [51]:
#Reconstruction based on reduced SVD, 2D case:  
u, s, vh = np.linalg.svd(a, full_matrices=False)
u.shape, s.shape, vh.shape
np.allclose(a, np.dot(u * s, vh))
smat = np.diag(s)
np.allclose(a, np.dot(u, np.dot(smat, vh)))

# Reconstruction based on full SVD, 4D case:
u, s, vh = np.linalg.svd(a, full_matrices=True)
u.shape, s.shape, vh.shape
np.allclose(a, np.matmul(u[..., :3] * s[..., None, :], vh))
np.allclose(a, np.matmul(u[..., :3], s[..., None] * vh))



#Reconstruction based on reduced SVD, 4D case:
u, s, vh = np.linalg.svd(a, full_matrices=False)
u.shape, s.shape, vh.shape
np.allclose(a, np.matmul(u * s[..., None, :], vh))
np.allclose(a, np.matmul(u, s[..., None] * vh))


True